# Generated by Django 2.2.6 on 2019-11-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191108_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='core.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homework/images'),
        ),
    ]
