# Generated by Django 2.2.6 on 2019-11-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191108_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
    ]
